name = "prism-vision-ai"
# Cloudflare Pages: use npm for installing/building and point to Vite output
pages_build_output_dir = "dist"

[build]
# Force npm for install + build on the platform
command = "npm ci && npm run build"